name: RTCAgent Builder

on:
  workflow_dispatch:
  release:
    types: [created]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Setup Build Env
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com//sipcapture/rtcagent/master/builder/init_env.sh)"
    - name: Build RTCAgent
      run: make
    - name: Check & Run
      run: |
        ls -alFh bin/rtcagent
        ./bin/rtcagent --help
    - name: Upload Release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          release_config: |
              ./bin/rtcagent
          tag_name: ${{ env.VERSION }}
          release_name: rtcagent_${{ github.ref_name }}
          draft: false
          prerelease: false
          overwrite: true
