name: RTCAgent Builder

on:
  workflow_dispatch:
  release:
    types: [created]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Setup Build Env
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com//sipcapture/rtcagent/master/builder/init_env.sh)"
    - name: Build RTCAgent
      run: make     
    - name: Compress
      run: |
        strip bin/rtcagent
        upx bin/rtcagent 
    - name: Check & Run
      run: |
        ls -alFh bin/rtcagent
        ./bin/rtcagent --help
        
    - name: Patch NFPM Version
      run: |
          sudo sed -i "s/0.0.0/${{ github.ref_name }}/g" rtcagent.yml
    - name: Create deb package
      id: nfpm-deb
      uses: burningalchemist/nfpm-action@v1
      env:
          VERSION: ${{ github.event.release.tag_name }}
      with:
          packager: deb
          config: rtcagent.yml
          target: rtcagent_${{  github.ref_name }}_all.deb
    - name: Create rpm package
      id: nfpm-rpm
      uses: burningalchemist/nfpm-action@v1
      env:
          VERSION: ${{ github.event.release.tag_name }}
      with:
          packager: rpm
          config: rtcagent.yml
          target: rtcagent_${{  github.ref_name }}.amd64.rpm
          
    - name: Upload Release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          release_config: |
              ./bin/rtcagent
              ./rtcagent_${{ github.ref_name }}_all.deb
              ./rtcagent_${{ github.ref_name }}.amd64.rpm
          tag_name: ${{ github.ref_name }}
          release_name: rtcagent_${{ github.ref_name }}
          draft: false
          prerelease: false
          overwrite: true    
        
